### ISSUE TITLE
Support ultra/matrix clean mode

### ISSUE THREAD

**Issue by adamk33n3r** [JeffResc/sharkiq#79]
As far as I can tell, all we can do is say "clean these rooms". I would like to be able to say "matrix clean the kitchen". At least in the app, matrix clean only supports a maximum of 1 room.

**Comment by MaxoOwen** [comment]
I'm unable to even get it to clean individual rooms. Right now they appear as attributes to me that I can't select. How did you get it to clean individual rooms? As a script? If so what's the right YAML to properly reference the correct room? ![image](https://github.com/user-attachments/assets/1d9dbf18-699c-4aa3-bec6-aad20821a24d)

**Comment by adamk33n3r** [comment]
I personally made buttons on a dashboard. I'm guessing there are other ways. Unfortunately I don't have the integration working right now (classic Auth errors).

From the button yaml:
```yaml
tap_action:
  action: perform-action
  perform_action: sharkiq.clean_room
  target:
    entity_id: vacuum.dustbin_bieber
  data:
    rooms:
      - kitchen
```
